[package]
name = "renderer_minifb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.23.0"

[profile.release]
opt-level = 0
codegen-units = 1
lto = true
panic = "abort"