[package]
name = "renderer_minifb"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.23.0"
fps_counter = "2.0.0"

[profile.release]
debug-assertions = false
debug = false
overflow-checks = false
strip = "symbols"
lto = true
opt-level = 0
panic = "abort"
